### ISSUE TITLE
Show a badge for Tasks that are Completed

### ISSUE THREAD

**Issue by AndyLee13** [CS2103JAN2017-W10-B4/main#103]
A tick badge for completed [tasks](https://www.google.com.sg/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwjXwsjT-vrSAhVKMY8KHVRrD5oQjRwIBw&url=http%3A%2F%2Fwww.tipsglobe.com%2F2014%2F09%2Ffacebook-verified-page-account.html&psig=AFQjCNEi1CAIcSd1x7uip-vO0Q-7CVfDow&ust=1490850755112501)
A exclamation mark badge for tasks that pend today [pending](https://www.google.com.sg/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwjZ7sCF-_rSAhWML48KHVWtAfUQjRwIBw&url=https%3A%2F%2Fwww.fotolia.com%2Fid%2F98045130&bvm=bv.150729734,d.c2I&psig=AFQjCNEvnlHIfJdJXIWYn4HCyzVzcBxmfQ&ust=1490851032551142)

**Comment by blakegoh** [comment]
done
