### ISSUE TITLE
V0.3 feedback

### ISSUE THREAD

**Issue by hwkchia** [CS2103JAN2017-W10-B4/main#91]
# User stories
👍 on categorizing the user stories. As you progress through the final weeks, just ensure that features mentioned in the user guide have corresponding user stories; however, some low priority user stories may be absent from the user guide.

# Use cases
Now that you have the functionality for adding different tasks, you need to have use cases represented these different adding functionalities.

# NFRs
Please include more of the project specific constraints?

# Product survey
👍 very extensive survey on the related products.

# Design document
👍 on fixing the diagrams to reflect your own product

# User guide
Remember to constantly update it to reflect the current status of your product. Keep in mind that the testers will be relying on the command summary to test your product, so make it a positive experience for them.

**Comment by AndyLee13** [comment]
@hwkchia Hi prof, Thank you very much for the review.
